const TABLE_SURFACE_RADIUS = 200;
const TABLE_CYLIDNER_HEIHGT = 13
const TABLE_CONE_HEIGHT = 80;
const TABLE_LEG_HEIGHT = 200;
const TABLE_LEG_RADIUS = 20;

function drawTable() {
  push()
  rotateX(-90)
  translate(0, TABLE_CYLIDNER_HEIHGT / 2, 0)
  cylinder(TABLE_SURFACE_RADIUS, TABLE_CYLIDNER_HEIHGT)
  pop()
  
  push()
  rotateX(-90)
  translate(0, TABLE_CYLIDNER_HEIHGT + TABLE_CONE_HEIGHT / 2, 0)
  cone(TABLE_SURFACE_RADIUS, TABLE_CONE_HEIGHT)
  pop()

  push()
  rotateX(90)
  translate(0, -(TABLE_CYLIDNER_HEIHGT + TABLE_CONE_HEIGHT / 2 + TABLE_LEG_HEIGHT / 2 - TABLE_CYLIDNER_HEIHGT * 0.2), 0)
  cylinder(TABLE_LEG_RADIUS, TABLE_LEG_HEIGHT)
  pop()

  push()
  rotateX(90)
  translate(0, -(TABLE_CYLIDNER_HEIHGT + TABLE_CONE_HEIGHT / 2 + TABLE_LEG_HEIGHT + TABLE_CYLIDNER_HEIHGT / 2), 0)
  cone(TABLE_SURFACE_RADIUS * 0.4, TABLE_CONE_HEIGHT * 0.5)
  pop()
}